# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joel/cakehonolulu/Risky

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joel/cakehonolulu/Risky

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joel/cakehonolulu/Risky/CMakeFiles /home/joel/cakehonolulu/Risky//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joel/cakehonolulu/Risky/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named risky

# Build rule for target.
risky: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 risky
.PHONY : risky

# fast build rule for target.
risky/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/build
.PHONY : risky/fast

external/ImGuiFileDialog/ImGuiFileDialog.o: external/ImGuiFileDialog/ImGuiFileDialog.cpp.o
.PHONY : external/ImGuiFileDialog/ImGuiFileDialog.o

# target to build an object file
external/ImGuiFileDialog/ImGuiFileDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/ImGuiFileDialog/ImGuiFileDialog.cpp.o
.PHONY : external/ImGuiFileDialog/ImGuiFileDialog.cpp.o

external/ImGuiFileDialog/ImGuiFileDialog.i: external/ImGuiFileDialog/ImGuiFileDialog.cpp.i
.PHONY : external/ImGuiFileDialog/ImGuiFileDialog.i

# target to preprocess a source file
external/ImGuiFileDialog/ImGuiFileDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/ImGuiFileDialog/ImGuiFileDialog.cpp.i
.PHONY : external/ImGuiFileDialog/ImGuiFileDialog.cpp.i

external/ImGuiFileDialog/ImGuiFileDialog.s: external/ImGuiFileDialog/ImGuiFileDialog.cpp.s
.PHONY : external/ImGuiFileDialog/ImGuiFileDialog.s

# target to generate assembly for a file
external/ImGuiFileDialog/ImGuiFileDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/ImGuiFileDialog/ImGuiFileDialog.cpp.s
.PHONY : external/ImGuiFileDialog/ImGuiFileDialog.cpp.s

external/imgui/backends/imgui_impl_opengl3.o: external/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : external/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
external/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : external/imgui/backends/imgui_impl_opengl3.cpp.o

external/imgui/backends/imgui_impl_opengl3.i: external/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : external/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
external/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : external/imgui/backends/imgui_impl_opengl3.cpp.i

external/imgui/backends/imgui_impl_opengl3.s: external/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : external/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
external/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : external/imgui/backends/imgui_impl_opengl3.cpp.s

external/imgui/backends/imgui_impl_sdl3.o: external/imgui/backends/imgui_impl_sdl3.cpp.o
.PHONY : external/imgui/backends/imgui_impl_sdl3.o

# target to build an object file
external/imgui/backends/imgui_impl_sdl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/backends/imgui_impl_sdl3.cpp.o
.PHONY : external/imgui/backends/imgui_impl_sdl3.cpp.o

external/imgui/backends/imgui_impl_sdl3.i: external/imgui/backends/imgui_impl_sdl3.cpp.i
.PHONY : external/imgui/backends/imgui_impl_sdl3.i

# target to preprocess a source file
external/imgui/backends/imgui_impl_sdl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/backends/imgui_impl_sdl3.cpp.i
.PHONY : external/imgui/backends/imgui_impl_sdl3.cpp.i

external/imgui/backends/imgui_impl_sdl3.s: external/imgui/backends/imgui_impl_sdl3.cpp.s
.PHONY : external/imgui/backends/imgui_impl_sdl3.s

# target to generate assembly for a file
external/imgui/backends/imgui_impl_sdl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/backends/imgui_impl_sdl3.cpp.s
.PHONY : external/imgui/backends/imgui_impl_sdl3.cpp.s

external/imgui/backends/imgui_impl_sdlrenderer3.o: external/imgui/backends/imgui_impl_sdlrenderer3.cpp.o
.PHONY : external/imgui/backends/imgui_impl_sdlrenderer3.o

# target to build an object file
external/imgui/backends/imgui_impl_sdlrenderer3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/backends/imgui_impl_sdlrenderer3.cpp.o
.PHONY : external/imgui/backends/imgui_impl_sdlrenderer3.cpp.o

external/imgui/backends/imgui_impl_sdlrenderer3.i: external/imgui/backends/imgui_impl_sdlrenderer3.cpp.i
.PHONY : external/imgui/backends/imgui_impl_sdlrenderer3.i

# target to preprocess a source file
external/imgui/backends/imgui_impl_sdlrenderer3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/backends/imgui_impl_sdlrenderer3.cpp.i
.PHONY : external/imgui/backends/imgui_impl_sdlrenderer3.cpp.i

external/imgui/backends/imgui_impl_sdlrenderer3.s: external/imgui/backends/imgui_impl_sdlrenderer3.cpp.s
.PHONY : external/imgui/backends/imgui_impl_sdlrenderer3.s

# target to generate assembly for a file
external/imgui/backends/imgui_impl_sdlrenderer3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/backends/imgui_impl_sdlrenderer3.cpp.s
.PHONY : external/imgui/backends/imgui_impl_sdlrenderer3.cpp.s

external/imgui/imgui.o: external/imgui/imgui.cpp.o
.PHONY : external/imgui/imgui.o

# target to build an object file
external/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/imgui.cpp.o
.PHONY : external/imgui/imgui.cpp.o

external/imgui/imgui.i: external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.i

# target to preprocess a source file
external/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.cpp.i

external/imgui/imgui.s: external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.s

# target to generate assembly for a file
external/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.cpp.s

external/imgui/imgui_draw.o: external/imgui/imgui_draw.cpp.o
.PHONY : external/imgui/imgui_draw.o

# target to build an object file
external/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/imgui_draw.cpp.o
.PHONY : external/imgui/imgui_draw.cpp.o

external/imgui/imgui_draw.i: external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.i

# target to preprocess a source file
external/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.cpp.i

external/imgui/imgui_draw.s: external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.s

# target to generate assembly for a file
external/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.cpp.s

external/imgui/imgui_tables.o: external/imgui/imgui_tables.cpp.o
.PHONY : external/imgui/imgui_tables.o

# target to build an object file
external/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/imgui_tables.cpp.o
.PHONY : external/imgui/imgui_tables.cpp.o

external/imgui/imgui_tables.i: external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.i

# target to preprocess a source file
external/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.cpp.i

external/imgui/imgui_tables.s: external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.s

# target to generate assembly for a file
external/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.cpp.s

external/imgui/imgui_widgets.o: external/imgui/imgui_widgets.cpp.o
.PHONY : external/imgui/imgui_widgets.o

# target to build an object file
external/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/imgui_widgets.cpp.o
.PHONY : external/imgui/imgui_widgets.cpp.o

external/imgui/imgui_widgets.i: external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.i

# target to preprocess a source file
external/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.cpp.i

external/imgui/imgui_widgets.s: external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.s

# target to generate assembly for a file
external/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.cpp.s

frontend/imgui/imgui_disassembler.o: frontend/imgui/imgui_disassembler.cpp.o
.PHONY : frontend/imgui/imgui_disassembler.o

# target to build an object file
frontend/imgui/imgui_disassembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/imgui_disassembler.cpp.o
.PHONY : frontend/imgui/imgui_disassembler.cpp.o

frontend/imgui/imgui_disassembler.i: frontend/imgui/imgui_disassembler.cpp.i
.PHONY : frontend/imgui/imgui_disassembler.i

# target to preprocess a source file
frontend/imgui/imgui_disassembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/imgui_disassembler.cpp.i
.PHONY : frontend/imgui/imgui_disassembler.cpp.i

frontend/imgui/imgui_disassembler.s: frontend/imgui/imgui_disassembler.cpp.s
.PHONY : frontend/imgui/imgui_disassembler.s

# target to generate assembly for a file
frontend/imgui/imgui_disassembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/imgui_disassembler.cpp.s
.PHONY : frontend/imgui/imgui_disassembler.cpp.s

frontend/imgui/imgui_exit.o: frontend/imgui/imgui_exit.cpp.o
.PHONY : frontend/imgui/imgui_exit.o

# target to build an object file
frontend/imgui/imgui_exit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/imgui_exit.cpp.o
.PHONY : frontend/imgui/imgui_exit.cpp.o

frontend/imgui/imgui_exit.i: frontend/imgui/imgui_exit.cpp.i
.PHONY : frontend/imgui/imgui_exit.i

# target to preprocess a source file
frontend/imgui/imgui_exit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/imgui_exit.cpp.i
.PHONY : frontend/imgui/imgui_exit.cpp.i

frontend/imgui/imgui_exit.s: frontend/imgui/imgui_exit.cpp.s
.PHONY : frontend/imgui/imgui_exit.s

# target to generate assembly for a file
frontend/imgui/imgui_exit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/imgui_exit.cpp.s
.PHONY : frontend/imgui/imgui_exit.cpp.s

frontend/imgui/imgui_log.o: frontend/imgui/imgui_log.cpp.o
.PHONY : frontend/imgui/imgui_log.o

# target to build an object file
frontend/imgui/imgui_log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/imgui_log.cpp.o
.PHONY : frontend/imgui/imgui_log.cpp.o

frontend/imgui/imgui_log.i: frontend/imgui/imgui_log.cpp.i
.PHONY : frontend/imgui/imgui_log.i

# target to preprocess a source file
frontend/imgui/imgui_log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/imgui_log.cpp.i
.PHONY : frontend/imgui/imgui_log.cpp.i

frontend/imgui/imgui_log.s: frontend/imgui/imgui_log.cpp.s
.PHONY : frontend/imgui/imgui_log.s

# target to generate assembly for a file
frontend/imgui/imgui_log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/imgui_log.cpp.s
.PHONY : frontend/imgui/imgui_log.cpp.s

frontend/imgui/imgui_risky.o: frontend/imgui/imgui_risky.cpp.o
.PHONY : frontend/imgui/imgui_risky.o

# target to build an object file
frontend/imgui/imgui_risky.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/imgui_risky.cpp.o
.PHONY : frontend/imgui/imgui_risky.cpp.o

frontend/imgui/imgui_risky.i: frontend/imgui/imgui_risky.cpp.i
.PHONY : frontend/imgui/imgui_risky.i

# target to preprocess a source file
frontend/imgui/imgui_risky.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/imgui_risky.cpp.i
.PHONY : frontend/imgui/imgui_risky.cpp.i

frontend/imgui/imgui_risky.s: frontend/imgui/imgui_risky.cpp.s
.PHONY : frontend/imgui/imgui_risky.s

# target to generate assembly for a file
frontend/imgui/imgui_risky.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/imgui_risky.cpp.s
.PHONY : frontend/imgui/imgui_risky.cpp.s

frontend/imgui/main.o: frontend/imgui/main.cpp.o
.PHONY : frontend/imgui/main.o

# target to build an object file
frontend/imgui/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/main.cpp.o
.PHONY : frontend/imgui/main.cpp.o

frontend/imgui/main.i: frontend/imgui/main.cpp.i
.PHONY : frontend/imgui/main.i

# target to preprocess a source file
frontend/imgui/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/main.cpp.i
.PHONY : frontend/imgui/main.cpp.i

frontend/imgui/main.s: frontend/imgui/main.cpp.s
.PHONY : frontend/imgui/main.s

# target to generate assembly for a file
frontend/imgui/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/frontend/imgui/main.cpp.s
.PHONY : frontend/imgui/main.cpp.s

src/bus/bus.o: src/bus/bus.cpp.o
.PHONY : src/bus/bus.o

# target to build an object file
src/bus/bus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/bus/bus.cpp.o
.PHONY : src/bus/bus.cpp.o

src/bus/bus.i: src/bus/bus.cpp.i
.PHONY : src/bus/bus.i

# target to preprocess a source file
src/bus/bus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/bus/bus.cpp.i
.PHONY : src/bus/bus.cpp.i

src/bus/bus.s: src/bus/bus.cpp.s
.PHONY : src/bus/bus.s

# target to generate assembly for a file
src/bus/bus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/bus/bus.cpp.s
.PHONY : src/bus/bus.cpp.s

src/cpu/core/rv32e.o: src/cpu/core/rv32e.cpp.o
.PHONY : src/cpu/core/rv32e.o

# target to build an object file
src/cpu/core/rv32e.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/cpu/core/rv32e.cpp.o
.PHONY : src/cpu/core/rv32e.cpp.o

src/cpu/core/rv32e.i: src/cpu/core/rv32e.cpp.i
.PHONY : src/cpu/core/rv32e.i

# target to preprocess a source file
src/cpu/core/rv32e.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/cpu/core/rv32e.cpp.i
.PHONY : src/cpu/core/rv32e.cpp.i

src/cpu/core/rv32e.s: src/cpu/core/rv32e.cpp.s
.PHONY : src/cpu/core/rv32e.s

# target to generate assembly for a file
src/cpu/core/rv32e.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/cpu/core/rv32e.cpp.s
.PHONY : src/cpu/core/rv32e.cpp.s

src/cpu/core/rv32i.o: src/cpu/core/rv32i.cpp.o
.PHONY : src/cpu/core/rv32i.o

# target to build an object file
src/cpu/core/rv32i.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/cpu/core/rv32i.cpp.o
.PHONY : src/cpu/core/rv32i.cpp.o

src/cpu/core/rv32i.i: src/cpu/core/rv32i.cpp.i
.PHONY : src/cpu/core/rv32i.i

# target to preprocess a source file
src/cpu/core/rv32i.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/cpu/core/rv32i.cpp.i
.PHONY : src/cpu/core/rv32i.cpp.i

src/cpu/core/rv32i.s: src/cpu/core/rv32i.cpp.s
.PHONY : src/cpu/core/rv32i.s

# target to generate assembly for a file
src/cpu/core/rv32i.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/cpu/core/rv32i.cpp.s
.PHONY : src/cpu/core/rv32i.cpp.s

src/cpu/core/rv64i.o: src/cpu/core/rv64i.cpp.o
.PHONY : src/cpu/core/rv64i.o

# target to build an object file
src/cpu/core/rv64i.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/cpu/core/rv64i.cpp.o
.PHONY : src/cpu/core/rv64i.cpp.o

src/cpu/core/rv64i.i: src/cpu/core/rv64i.cpp.i
.PHONY : src/cpu/core/rv64i.i

# target to preprocess a source file
src/cpu/core/rv64i.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/cpu/core/rv64i.cpp.i
.PHONY : src/cpu/core/rv64i.cpp.i

src/cpu/core/rv64i.s: src/cpu/core/rv64i.cpp.s
.PHONY : src/cpu/core/rv64i.s

# target to generate assembly for a file
src/cpu/core/rv64i.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/cpu/core/rv64i.cpp.s
.PHONY : src/cpu/core/rv64i.cpp.s

src/cpu/disassembler.o: src/cpu/disassembler.cpp.o
.PHONY : src/cpu/disassembler.o

# target to build an object file
src/cpu/disassembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/cpu/disassembler.cpp.o
.PHONY : src/cpu/disassembler.cpp.o

src/cpu/disassembler.i: src/cpu/disassembler.cpp.i
.PHONY : src/cpu/disassembler.i

# target to preprocess a source file
src/cpu/disassembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/cpu/disassembler.cpp.i
.PHONY : src/cpu/disassembler.cpp.i

src/cpu/disassembler.s: src/cpu/disassembler.cpp.s
.PHONY : src/cpu/disassembler.s

# target to generate assembly for a file
src/cpu/disassembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/cpu/disassembler.cpp.s
.PHONY : src/cpu/disassembler.cpp.s

src/log/log.o: src/log/log.cpp.o
.PHONY : src/log/log.o

# target to build an object file
src/log/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/log/log.cpp.o
.PHONY : src/log/log.cpp.o

src/log/log.i: src/log/log.cpp.i
.PHONY : src/log/log.i

# target to preprocess a source file
src/log/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/log/log.cpp.i
.PHONY : src/log/log.cpp.i

src/log/log.s: src/log/log.cpp.s
.PHONY : src/log/log.s

# target to generate assembly for a file
src/log/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/log/log.cpp.s
.PHONY : src/log/log.cpp.s

src/risky.o: src/risky.cpp.o
.PHONY : src/risky.o

# target to build an object file
src/risky.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/risky.cpp.o
.PHONY : src/risky.cpp.o

src/risky.i: src/risky.cpp.i
.PHONY : src/risky.i

# target to preprocess a source file
src/risky.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/risky.cpp.i
.PHONY : src/risky.cpp.i

src/risky.s: src/risky.cpp.s
.PHONY : src/risky.s

# target to generate assembly for a file
src/risky.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/risky.cpp.s
.PHONY : src/risky.cpp.s

src/utils/symbols.o: src/utils/symbols.cpp.o
.PHONY : src/utils/symbols.o

# target to build an object file
src/utils/symbols.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/utils/symbols.cpp.o
.PHONY : src/utils/symbols.cpp.o

src/utils/symbols.i: src/utils/symbols.cpp.i
.PHONY : src/utils/symbols.i

# target to preprocess a source file
src/utils/symbols.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/utils/symbols.cpp.i
.PHONY : src/utils/symbols.cpp.i

src/utils/symbols.s: src/utils/symbols.cpp.s
.PHONY : src/utils/symbols.s

# target to generate assembly for a file
src/utils/symbols.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/risky.dir/build.make CMakeFiles/risky.dir/src/utils/symbols.cpp.s
.PHONY : src/utils/symbols.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... risky"
	@echo "... external/ImGuiFileDialog/ImGuiFileDialog.o"
	@echo "... external/ImGuiFileDialog/ImGuiFileDialog.i"
	@echo "... external/ImGuiFileDialog/ImGuiFileDialog.s"
	@echo "... external/imgui/backends/imgui_impl_opengl3.o"
	@echo "... external/imgui/backends/imgui_impl_opengl3.i"
	@echo "... external/imgui/backends/imgui_impl_opengl3.s"
	@echo "... external/imgui/backends/imgui_impl_sdl3.o"
	@echo "... external/imgui/backends/imgui_impl_sdl3.i"
	@echo "... external/imgui/backends/imgui_impl_sdl3.s"
	@echo "... external/imgui/backends/imgui_impl_sdlrenderer3.o"
	@echo "... external/imgui/backends/imgui_impl_sdlrenderer3.i"
	@echo "... external/imgui/backends/imgui_impl_sdlrenderer3.s"
	@echo "... external/imgui/imgui.o"
	@echo "... external/imgui/imgui.i"
	@echo "... external/imgui/imgui.s"
	@echo "... external/imgui/imgui_draw.o"
	@echo "... external/imgui/imgui_draw.i"
	@echo "... external/imgui/imgui_draw.s"
	@echo "... external/imgui/imgui_tables.o"
	@echo "... external/imgui/imgui_tables.i"
	@echo "... external/imgui/imgui_tables.s"
	@echo "... external/imgui/imgui_widgets.o"
	@echo "... external/imgui/imgui_widgets.i"
	@echo "... external/imgui/imgui_widgets.s"
	@echo "... frontend/imgui/imgui_disassembler.o"
	@echo "... frontend/imgui/imgui_disassembler.i"
	@echo "... frontend/imgui/imgui_disassembler.s"
	@echo "... frontend/imgui/imgui_exit.o"
	@echo "... frontend/imgui/imgui_exit.i"
	@echo "... frontend/imgui/imgui_exit.s"
	@echo "... frontend/imgui/imgui_log.o"
	@echo "... frontend/imgui/imgui_log.i"
	@echo "... frontend/imgui/imgui_log.s"
	@echo "... frontend/imgui/imgui_risky.o"
	@echo "... frontend/imgui/imgui_risky.i"
	@echo "... frontend/imgui/imgui_risky.s"
	@echo "... frontend/imgui/main.o"
	@echo "... frontend/imgui/main.i"
	@echo "... frontend/imgui/main.s"
	@echo "... src/bus/bus.o"
	@echo "... src/bus/bus.i"
	@echo "... src/bus/bus.s"
	@echo "... src/cpu/core/rv32e.o"
	@echo "... src/cpu/core/rv32e.i"
	@echo "... src/cpu/core/rv32e.s"
	@echo "... src/cpu/core/rv32i.o"
	@echo "... src/cpu/core/rv32i.i"
	@echo "... src/cpu/core/rv32i.s"
	@echo "... src/cpu/core/rv64i.o"
	@echo "... src/cpu/core/rv64i.i"
	@echo "... src/cpu/core/rv64i.s"
	@echo "... src/cpu/disassembler.o"
	@echo "... src/cpu/disassembler.i"
	@echo "... src/cpu/disassembler.s"
	@echo "... src/log/log.o"
	@echo "... src/log/log.i"
	@echo "... src/log/log.s"
	@echo "... src/risky.o"
	@echo "... src/risky.i"
	@echo "... src/risky.s"
	@echo "... src/utils/symbols.o"
	@echo "... src/utils/symbols.i"
	@echo "... src/utils/symbols.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

